### ISSUE TITLE
Error connecting to the spirent server test sesson 

### ISSUE THREAD

**Issue by KetanBansal** [Spirent/py-stcrestclient#24]
from stcrestclient import stchttp
stc = stchttp.StcHttp('10.192.116.1')
stc.set_timeout(5)
sid = stc.new_session('abc', 'Password1234!')
print(type(sid))
stc.system_info()
---------------------------------------------------------------------------------------------------------------
When i am trying to connect to the server it is giving me the error below.

Traceback (most recent call last):
  File "testing_spirent.py", line 17, in <module>
    sid = stc.new_session('abc', 'Password1234!')
  File "/usr/local/lib/python3.6/site-packages/stcrestclient/stchttp.py", line 135, in new_session
    sid = data['session_id']
TypeError: string indices must be integers

**Comment by KetanBansal** [comment]
mohit@automationvm Spirent_testing]$ python -m stcrestclient.systeminfo "10.192.116.1"
ERROR string indices must be integers, not str
[mohit@automationvm Spirent_testing]$ stcinfo 10.192.116.1
ERROR string indices must be integers

**Comment by jmkho-spirent** [comment]
Sorry for the delayed response. Are you running against stcweb or a labserver? Which version of STC are you using?
